services:
  recipesearchapi:
    image: recipesearchapi
    depends_on:
      recipe_db:
        condition: service_healthy
    build:
      context: .
      dockerfile: recipe-search-api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5198:5198
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
  recipe_db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=api_user
    ports:
      - "5334:5432"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=pass
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "16543:80"
    restart: unless-stopped
volumes:
  db:
