services:
  db:
    container_name: recipe_db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pass
    ports:
      - "5334:5432"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data 

volumes:
  db: